### ISSUE TITLE
Option to not delete the tags

### ISSUE THREAD

**Issue by gamelaster** [onyxmueller/build-tag-number#10]
Hello,

I want to use the existing build-number- tags in Releases, so I don't need to delete them.
Would be this possible?

Thank you :)

**Comment by onyxmueller** [comment]
Hi! This is definitely possible. And it makes sense! But I don't really have any plans to add new features to this action any time soon. The beauty of open source though, is that you can just fork this repo and modify things to suit your needs. 😀
