### ISSUE TITLE
Change the Too many refs in repository error to warning 

### ISSUE THREAD

**Issue by oferqm** [onyxmueller/build-tag-number#11]
At the action, we have a check for old tags with the same prefix, and if we have more than 5 tags matching the search we exit with an error.

I think that this is overkill and it is unnecessary to fail jobs/build just because of that. It is better to change it to a warning.

Also maybe adding a flag that will clean it automatically.

i am talking about the code at main.js line 98

            const MAX_OLD_NUMBERS = 5; //One or two ref deletes might fail, but if we have lots then there's something wrong!
            if (nrTags.length > MAX_OLD_NUMBERS) {
                fail(`ERROR: Too many ${prefix}build-number- refs in repository, found ${nrTags.length}, expected only 1. Check your tags!`);
            }

**Comment by onyxmueller** [comment]
Hello. This is by design - it's an opinionated approach that assumes there should only be one build number/tag per use-case. Any more is pollution.

The beauty of open source is that you are welcome to fork this repo and use your own copy. I don't really have any plans to change this behavior.
