### ISSUE TITLE
Update `v1` tag to point to latest 1.x.x release

### ISSUE THREAD

**Issue by charliealbright** [onyxmueller/build-tag-number#15]
Hey there,

Wondering if you could update the `v1` tag to point to your latest release - that way anyone referencing `v1` of your action will automatically get updates. Here's an article on Github's recommended tagging practice for Actions: 

https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management

**Comment by onyxmueller** [comment]
Done! Good lookin' out. I totally forgot to move that tag up.

**Comment by tim-altitudegames** [comment]
Might need to be done once more now that 1.0.4 is out 👀

**Comment by onyxmueller** [comment]
> Might need to be done once more now that 1.0.4 is out 👀

That's done now. I really need to automate that. 😛
